[package]
name = "abs"
version = "0.1.0"
edition = "2024"

[dependencies]
adxl345_driver2 = "2.0.1"
anyhow = "1.0.100"
log = "0.4.28"
rppal = { version = "0.22.1", features = ["embedded-hal"] }
simplelog = "0.12.2"
